<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="4" total="7" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="11701" started-at="2022-01-29T03:47:11Z" finished-at="2022-01-29T03:47:23Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="11701" started-at="2022-01-29T03:47:11Z" finished-at="2022-01-29T03:47:23Z">
      <class name="testCase.TC003PayBillSprint">
        <test-method status="PASS" signature="payBillSprint()[pri:2, instance:testCase.TC003PayBillSprint@68e5eea7]" name="payBillSprint" duration-ms="2017" started-at="2022-01-28T22:47:20Z" finished-at="2022-01-28T22:47:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- payBillSprint -->
      </class> <!-- testCase.TC003PayBillSprint -->
      <class name="testCase.TC002AddNewPayee">
        <test-method status="PASS" signature="init()[pri:0, instance:testCase.TC002AddNewPayee@38e79ae3]" name="init" is-config="true" duration-ms="3994" started-at="2022-01-28T22:47:07Z" finished-at="2022-01-28T22:47:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="AddPayee()[pri:1, instance:testCase.TC002AddNewPayee@38e79ae3]" name="AddPayee" duration-ms="1911" started-at="2022-01-28T22:47:19Z" finished-at="2022-01-28T22:47:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddPayee -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testCase.TC002AddNewPayee@38e79ae3]" name="tearDown" is-config="true" duration-ms="1361" started-at="2022-01-28T22:47:23Z" finished-at="2022-01-28T22:47:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testCase.TC002AddNewPayee -->
      <class name="testCase.TC001Login">
        <test-method status="FAIL" signature="verifyLogin()[pri:0, instance:testCase.TC001Login@63070bab]" name="verifyLogin" duration-ms="6543" started-at="2022-01-28T22:47:11Z" finished-at="2022-01-28T22:47:17Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Zero -Account Summary] but found [Zero - Account Summary]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Zero -Account Summary] but found [Zero - Account Summary]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at testCase.TC001Login.verifyLogin(TC001Login.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogin -->
      </class> <!-- testCase.TC001Login -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
